apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend-shopping-cart
  namespaceSelector:
    any: true
  endpoints:
    - port: http-metrics
      interval: 15s
