apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.21.0
      ports:
        - containerPort: 80
    - name: busybox
      image: busybox:1.35
      command:
        [
          "/bin/sh",
          "-c",
          "while true; do echo 'Hello from busybox' >> /var/log/busybox.log; sleep 5; done",
        ]
      volumeMounts:
        - name: log-volume
          mountPath: /var/log
  volumes:
    - name: log-volume
      emptyDir: {}
