apiVersion: v1
kind: Pod
metadata:
  name: pod-with-toleration
spec:
  containers:
    - name: my-app
      image: busybox
      command: ["sh", "-c", 'echo "Hello, Toleration!" && sleep 3600']
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
