apiVersion: v1
kind: Pod
metadata:
  name: rbac-test-pod
  namespace: rbac-demo
spec:
  serviceAccountName: pod-reader-sa
  containers:
    - name: kubectl-container
      image: bitnami/kubectl
      command: ["sh", "-c", "kubectl get pods -n rbac-demo && sleep 3600"]
  restartPolicy: Never
