apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  containers:
    - name: my-app
      image: busybox
      command:
        [
          "sh",
          "-c",
          "echo App Mode: $APP_MODE && echo DB User: $DB_USER && echo DB Pass: $DB_PASSWORD && sleep 3600",
        ]
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secret
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
  restartPolicy: Never
