apiVersion: v1
kind: Pod
metadata:
  name: pod-with-config-volume
spec:
  containers:
    - name: nginx
      image: nginx:1.21.0
      volumeMounts:
        - name: config-map-volume
          mountPath: /etc/config
        - name: secret-volume
          mountPath: /etc/secret
          readOnly: true
  volumes:
    - name: config-map-volume
      configMap:
        name: my-configmap
    - name: secret-volume
      secret:
        secretName: my-secret
