apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-pi-calculation
spec:
  completions: 4 # Number of pods to complete
  parallelism: 2 # Number of pods to run at once
  template:
    spec:
      containers:
        - name: pi
          image: perl:5.34
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
