apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tapaspcs/kubernetes-basics-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: "db-service"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-shopping-cart
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 3001
      targetPort: 3001
    - name: http-metrics
      port: 3002
      targetPort: 3001
