apiVersion: v1
kind: Pod
metadata:
  name: pod-with-emptydir
spec:
  containers:
    - name: nginx
      image: nginx:1.21.0
      volumeMounts:
        - name: cache-volume
          mountPath: /cache
    - name: logger
      image: busybox:1.35
      command:
        ["/bin/sh", "-c", "while true; do date >> /data/log.txt; sleep 5; done"]
      volumeMounts:
        - name: cache-volume
          mountPath: /data
  volumes:
    - name: cache-volume
      emptyDir: {}
