apiVersion: v1
kind: Pod
metadata:
  name: pod-with-pvc
spec:
  containers:
    - name: my-app
      image: busybox
      command:
        [
          "sh",
          "-c",
          "echo 'Hello from my-app writing to a PVC' > /data/hello.txt && cat /data/hello.txt && sleep 3600",
        ]
      volumeMounts:
        - mountPath: "/data"
          name: data-vol
  volumes:
    - name: data-vol
      persistentVolumeClaim:
        claimName: pvc-demo
